### ISSUE TITLE
Tratamento exceção ao atualizar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [mpsdecamargo/dscrud#1]
Olá mpsdecamargo, sou o Alexandre e estou corrigindo sua atividade.

Seu trabalho foi aceito, parabéns! Porém, faltou fazer o tratamento de exceções. Está retornando erro 500 ao **atualizar** o cliente quando é informado um id que não existe.

Abraço e bons estudos

**Comment by mpsdecamargo** [comment]
Olá, Alexandre!

Obrigado pela correção, já alterei o código trocando a EntityNotFoundException por ResourceNotFoundException. Depois disso tudo está funcionando.
